### ISSUE TITLE
Deberíamos agregar los archivos autogenerados al .gitignore

### ISSUE THREAD

**Issue by eatskolnikov** [xpostudio4/metacommunity#11]
Me refiero a especificamente al main.css y main.min.css. Deberíamos eliminarlos y ponerlos en el gitignore.

**Comment by francisbrito** [comment]
En adición a esos, diría que también hay que ignorar los archivos comunes de Node.js y editores comunes.

**Comment by eatskolnikov** [comment]
@francisbrito uhum, en este repositorio tienen ejemplos de gitignores para cada caso https://github.com/github/gitignore vamos a tomar el que mas convenga

**Comment by rapito** [comment]
+1

**Comment by xpostudio4** [comment]
Entiendo @francisbrito que mejoraste esto con el commit #24
