### ISSUE TITLE
Agregar estaticamente la lista de los Proximos Eventos a la sección 'Proximos Eventos'

### ISSUE THREAD

**Issue by francisbrito** [xpostudio4/metacommunity#29]
La intención de esta tarea es poder desplegar un listado de eventos _fijos_ cuando se acceda a `/events`. Inicialmente se consideró que la data provenga desde un archivo en el sistema, sin embargo, sería ideal poder traer esa información desde Facebook o bien un archivo en Google Drive o Google Calendar.

**Comment by eatskolnikov** [comment]
{
"events":[{
  "title": "Introduccion a KoaJS",
  "speaker": "Juan Perez",
  "Date": "2016-04-05 19:00",
  "Thumbnail_url": "http://sdsdfsdf.jpg"
}]
}

**Comment by francisbrito** [comment]
De donde sacariamos la información del charlista?

**Comment by xpostudio4** [comment]
Normalmente esta en las publicaciones de los eventos

On Thu, Mar 31, 2016 at 6:20 PM, Francis Brito notifications@github.com
wrote:

> De donde sacariamos la información del charlista?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/xpostudio4/metacommunity/issues/29#issuecomment-204155136

## 

Leonardo Jimenez
_Chief Executive Officer + Co-founder_
Office:  (781) 247-5020 (US)
            (809) 685-7720 (DR)
Cellphone : (809) 875-5425 (DR)
leonardo@codetiger.co

**Comment by francisbrito** [comment]
@xpostudio4 Como extraeriamos **programáticamente** el nombre del charlista de la siguiente publicación?

> Has oido un mundo sobre React y lo poderoso que es, en esta charla te compartiremos todo lo que necesitas para empezar a usarla y las buenas practicas que el equipo de Rev.com ha aprendido luego de implementar React en su aplicación.
> 
> En esta charla **Nazaret Ramirez** nos estara hablando de las mejores practicas para trabajar con este tipo de aplicaciones.
> 
> Nazaret, es Software Developer en rev.com, donde trabaja en todo el stack de una interesante aplicación.
> 
> El evento es gratis y está pautado para el LUNES 28 de Marzo del 2016, a partir de las 7:00 PM en el espacio de Microsoft Dominicana en Blue Mall.
> 
> Ubicación en Google Maps: http://bit.ly/1T9IJ4i

**Comment by eatskolnikov** [comment]
No way, la única forma sería quedar de acuerdo en establecer un formato para escribir la descripción de los eventos, es la única forma en que podríamos parsear con 100% de precisión el valor. Algo como agregar al final de la descripción:

```
Charlista: Nazaret Ramirez
```

y entonces puedes hacer un split por el string "Charlista:", tomar el lado derecho, trimearlo y tienes el nombre.

**Comment by francisbrito** [comment]
Esto está listo desde: https://github.com/xpostudio4/metacommunity/pull/48
