### ISSUE TITLE
Cambiar opción del menú principal "Charlistas" para que apunte al segmento "Charlistas" del Home Page

### ISSUE THREAD

**Issue by francisbrito** [xpostudio4/metacommunity#32]

**Comment by xpostudio4** [comment]
Esto no me hace sentido. Como quiera el detalle de abajo va a dirigir a la pagina de charlistas.

**Comment by xpostudio4** [comment]
Creo que este issue debe ser eliminado y en vez de eso terminarse la pagina de ser charlista. En particular me puedo comprometer a tener eso listo esta semana @francisbrito .

**Comment by francisbrito** [comment]
_Copiado de Slack_

> @xpostudio4 entiendo que deberíamos discutirlo antes de cerrarlo. Si lo que se desea es que no se trabaje en el issue porque es incierto el porque del mismo, convendría etiquetar lo de alguna manera que indique esto. Algo así como "discussing" o "pending group approval".
> 
> Dicho esto, la idea detrás de ese issue y el resto de los issues relacionados a segmentos es proveer la información en la página principal como una sección HTML, imitando la estructura de información que tiene la antigua versión de Meta. @claudio quizás pueda profundizar sobre la decisión
