### ISSUE TITLE
Enrutar opciones del footer

### ISSUE THREAD

**Issue by francisbrito** [xpostudio4/metacommunity#34]
Nosotros -> `/about-us`
Patrocinadores -> `/index#sponsors`
Dona a la comunidad -> `/donations`
Se un charlista -> Google Form para agregar charlistas
Próximos eventos -> `/index#Eventos`
Lista de comunidades -> `/about-us#user-groups`

**Comment by modestofiguereo** [comment]
@francisbrito Las opciones del footer ya tienen sus respectivas rutas.

**Comment by francisbrito** [comment]
Gracias por apuntarnos esto @ModestoFiguereo
