### ISSUE TITLE
Fix display of sponsors

### ISSUE THREAD

**Issue by xpostudio4** [xpostudio4/metacommunity#52]
Hey @viviangb , con el pull request en https://github.com/xpostudio4/metacommunity/pull/50, se colocaron todos los patrocinadores juntos, esto debería ser un carrusel donde se presenten solo cierta cantidad de los patrocinadores al mismo tiempo, como en el mockup. 

Can you fix it please?

**Comment by vivgui** [comment]
@xpostudio4 fixed
