### ISSUE TITLE
Hacer mas visible la 404

### ISSUE THREAD

**Issue by xpostudio4** [xpostudio4/metacommunity#7]
Esta es una idea, pero igual puede ser algo mas interesante.
- http://codepen.io/mistic100/pen/zAren

**Comment by alblandino** [comment]
Mmmmm, veo eso demasiado estrambotico para un 404 en este tipo de páginas, vere como poner a un compañero a hacer una propuesta de UI para el site

**Comment by vivgui** [comment]
@xpostudio4 chequeala ahora

**Comment by xpostudio4** [comment]
Muy apero lo del gato

**Comment by xpostudio4** [comment]
Aunque sería bueno que en vez de bonito dijera "este hermoso gato"

**Comment by vivgui** [comment]
ok ahora lo cambio

**Comment by vivgui** [comment]
changed
